---
- name: Purge Apache
  apt:
    state: absent
    purge: true
    name:
      - apache2
      - apache2-bin
      - apache2-data
      - apache2-utils

- name: Delete Apache configuration
  file:
    state: absent
    path: '{{ common__apache__conf_dir }}'
