---
- name: Install basic packages
  apt:
    name:
      - apt-transport-https
      - curl
      - gnupg
      - gnupg2
      - procps
      - software-properties-common
      - wget

- name: Install additional packages
  apt:
    name: '{{ common__basics__additional_packages }}'
