---
- name: Install basic packages
  apt:
    name:
      - apt-transport-https
      - build-essential
      - curl
      - git
      - gnupg
      - gnupg2
      - net-tools
      - procps
      - software-properties-common
      - unzip
      - wget
      - zip

- name: Install additional packages
  apt:
    name: '{{ common__basics__additional_packages }}'
