---
- include_tasks: basics.yml
- include_tasks: usability.yml
- include_tasks: ssh.yml
- include_tasks: iptables.yml
- include_tasks: certbot.yml

- include_tasks: apache.yml
  when: common__apache__state == 'install'
- meta: flush_handlers

- include_tasks: nginx.yml
  when: common__nginx__state == 'install'
- meta: flush_handlers
