---
- include_tasks: basics.yml
  when: >-
    'basics'    in common__scenarios or
    'usability' in common__scenarios

- include_tasks: usability.yml
  when: >-
    'usability' in common__scenarios

- include_tasks: ssh.yml
  when: >-
    'ssh' in common__scenarios

- include_tasks: iptables.yml
  when: >-
    'iptables' in common__scenarios

- include_tasks: certbot.yml
  when: >-
    'certbot' in common__scenarios

- include_tasks: nginx.yml
  when: >-
    'nginx' in common__scenarios
