---
- include_tasks: basics.yml
- include_tasks: usability.yml
- include_tasks: ssh.yml
- include_tasks: iptables.yml
- include_tasks: certbot.yml
- meta: flush_handlers

- include_tasks: apache/purge.yml
  when: common__apache__state == 'purge'
- include_tasks: apache/install.yml
  when: common__apache__state == 'install'
- meta: flush_handlers

- include_tasks: nginx/purge.yml
  when: common__nginx__state == 'purge'
- include_tasks: nginx/install.yml
  when: common__nginx__state == 'install'
- meta: flush_handlers
