---
- include_tasks: basics.yml
- include_tasks: usability.yml
- include_tasks: ssh.yml
- include_tasks: iptables.yml
- include_tasks: certbot.yml
- include_tasks: nginx.yml
- include_tasks: apache.yml
