---
- name: Install useful packages
  apt:
    name: ['bash-completion', 'colordiff', 'curl', 'less', 'vim']

- name: Install Vim config
  copy:
    src: files/usability/vimrc.local
    dest: /etc/vim/vimrc.local
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root

- name: Set Vim as default editor
  alternatives:
    name: editor
    path: /usr/bin/vim.basic
