---
- name: common | Restart SSH daemon
  systemd:
    daemon_reload: true
    name: sshd
    state: restarted

- name: common | Load iptables rules for IPv4
  shell: 'cat {{ common__iptables__conf_ipv4 }} | iptables-restore'

- name: common | Load iptables rules for IPv6
  shell: 'cat {{ common__iptables__conf_ipv6 }} | ip6tables-restore'

- name: common | Restart Nginx
  systemd:
    daemon_reload: true
    name: nginx
    state: restarted

- name: common | Restart Apache
  systemd:
    daemon_reload: true
    name: apache2
    state: restarted
