---
- name: Converge
  hosts: all
  module_defaults:
    apt:
      force_apt_get: true
      cache_valid_time: 86400
  roles:
    - role: common
      become: true
      vars:
        common__certbot__run: false
